# Generated by Django 6.0.2 on 2026-02-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'NGOs',
            },
        ),
        migrations.CreateModel(
            name='NGOAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(default='General', max_length=80)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('service_date', models.DateTimeField()),
                ('cutoff_time', models.DateTimeField()),
                ('max_slots', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='ngo.ngo')),
            ],
            options={
                'verbose_name_plural': 'NGOAvailabilities',
            },
        ),
        migrations.DeleteModel(
            name='NGOActivity',
        ),
        migrations.CreateModel(
            name='NGOActivity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ngo.ngoavailability',),
        ),
    ]
