# Generated by Django 6.0.1 on 2026-03-25 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_ngo_ngoavailability_delete_ngoactivity_ngoactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={'ordering': ['name'], 'verbose_name_plural': 'NGOs'},
        ),
        migrations.AlterModelOptions(
            name='ngoavailability',
            options={'ordering': ['service_date', 'ngo__name'], 'verbose_name_plural': 'NGOAvailabilities'},
        ),
        migrations.AddField(
            model_name='ngo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ngo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ngoavailability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='ngoavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
