# Generated by Django 5.2.11 on 2026-04-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_alter_ngo_id_alter_ngoavailability_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ngoavailability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
