# Generated by Django 6.0.2 on 2026-02-17 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_ngo_ngoavailability_delete_ngoactivity_ngoactivity'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.ngoavailability'),
        ),
    ]
