# Generated by Django 6.0.1 on 2026-03-25 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_alter_ngo_options_alter_ngoavailability_options_and_more'),
        ('registrations', '0002_alter_registration_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AlterField(
            model_name='registration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ngo.ngoavailability'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('employee', 'activity'), name='unique_employee_activity_registration'),
        ),
    ]
