# Generated by Django 5.2.11 on 2026-04-26 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0005_alter_ngo_id_alter_ngoavailability_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('reminder', 'Reminder'), ('broadcast', 'Broadcast'), ('scheduled', 'Scheduled Reminder')], max_length=20)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('audience', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('result_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_jobs', to='ngo.ngoavailability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
